### ISSUE TITLE
Could this make the total time even shorter?

### ISSUE THREAD

**Issue by Fyod** [makermoekoe/Picoclick-C3#13]
I was browsing around some ESP32 troubleshooting and found this interesting issue over at Espressif's GitHub https://github.com/espressif/esp-idf/pull/5777 but I don't know if this pertains to the C3 as well.

> By calibrating only when necessary, ESP32 wakeup to app_main entry is reduced from 27ms to 17ms; more significantly, ESP32-S2 is reduced from 90ms to 17ms.

Cheers!

**Comment by makermoekoe** [comment]
Seems like an easy way to reduce boot up time, but unfortunately I cannot find the file in the esp-idf folder for the ESP32C3.

Nevertheless there is a line in the menuconfig which says "Number of cycles for RTC_SLOW_CLK calibration". Seems like it is almost the same 😄 It is currently set to 1024. I will check the behavior of reducing this value soon!

**Comment by Fyod** [comment]
Sweet! Hope it helps. Every millisecond counts 😉

**Comment by Fyod** [comment]
Over 10%, not bad! Nearly reaching standard internet ping times, lol.

Slightly related - Is connecting to a wifi AP out of question? It would likely take many seconds?

**Comment by makermoekoe** [comment]
We've found a new solution which was discussed [here](https://github.com/espressif/esp-idf/issues/8390).

It uses the VDD_SPI pin of the chip as the latch pin. Once enabling deep sleep of the MCU the chip will shut down the flash to save power, which will shutdown the complete Picoclick as well.

**Comment by joba-1** [comment]
Thanks, very clever solution - as long as you have access to that line. 
I mostly don't have, and I like that the RC solution seems quite universal and chip independent. Guess I'll try and see if there are drawbacks when I need it.
