### ISSUE TITLE
Improve reference designators and orientation of U2

### ISSUE THREAD

**Issue by poysh** [makermoekoe/Picoclick-C3#15]
I managed to assemble the top part of the PCB today with some minor hiccups. Please don't pay too much attention to the solder joints. All components are sourced from Digikey and Mouser with some replacements for parts which were not available. 
The hardest part was finding the reference designators on the board drawing and the only workaround was loading the board file into an online viewer and trying to match it. A graphic with good readable reference designators would be a huge help. 

Another small problem was trying to find the right orientation of U2 as I couldn't find a dot on the PCB to match the component. After checking the documention of the component and the schematics I was able to narrow it down. 

I can try to update the footprint after getting familiar with Eagle and commit a merge request if that helps you. 

![photo_2022-02-17_19-30-39](https://user-images.githubusercontent.com/10188657/154556630-76e6aeb9-d37b-42ec-b2f2-00e6c392b548.jpg)

**Comment by makermoekoe** [comment]
Great work! Glad somebody tries to solder it himself. 
Sorry for the bad labeling, it is fixed now.
