### ISSUE TITLE
Battery discharge at boot?

### ISSUE THREAD

**Issue by gnistregn** [makermoekoe/Picoclick-C3#16]
How come the low discharge rate of such a small battery doesn't cause a brownout when it draws 200+ mA at boot?

**Comment by Fyod** [comment]
When I looked into this, I found someone who tested 2x and 3x discharge rate of small cells. It still works, but may affect overall battery life, though not significantly. The discharge rates that manufacturers (brand names like Panasonic) guarantee are best practice that ensures long life.
I don't think voltage sag will be an issue here. it can of course be mitigated with capacitors.
