### ISSUE TITLE
Antenna impedance matching: F2 unknown

### ISSUE THREAD

**Issue by fgardt** [makermoekoe/Picoclick-C3#18]
The part named F2 in schematic and BOM has a value of 0. What would be the correct value here?

(also: since I can‘t find any info on this anywhere, do you know the impedance of the ESP32-C3 itself?)

**Comment by fg89o** [comment]
May be i am wrong, but i think is a 0 ohm resistor.

**Comment by makermoekoe** [comment]
F2 is just a bridge (0Ohm resistor), and for the C3T there isn't any matching network and impedance matching done. The C3 includes a PI-network and is properly tuned.
