### ISSUE TITLE
Have BOM list ?

### ISSUE THREAD

**Issue by Witawat** [makermoekoe/Picoclick-C3#2]
![image](https://user-images.githubusercontent.com/4926369/148866935-79b6a86f-8a04-4ff8-93e9-5041efeb7872.png)
What part F1 and F2 ?

thankyou

**Comment by frollard** [comment]
https://www.espressif.com/sites/default/files/documentation/esp32-c3_hardware_design_guidelines_en.pdf

page 11: section 2.5 RF hardware design notes - "add a pi matching network for antenna matching, preferably CLC network." Parts tbd based on actual pcb.

**Comment by makermoekoe** [comment]
Tradeoff between device size and fully matchable antenna. So it's not a complete pi network but nevertheless seems to work fine for this four layer board with its dimensions.

BOM is added.
