### ISSUE TITLE
Schematics missing for Picoclick C3

### ISSUE THREAD

**Issue by septatrix** [makermoekoe/Picoclick-C3#22]
I just finished watched the YouTube video and came to check for the schematics. However they do not seem to be pushed yet.

Can you tell when we can expect to see them?

**Comment by WoodwindHu** [comment]
Same question

**Comment by janausis** [comment]
Is there an update on if or when the Schematics will be added?

**Comment by Ponti17** [comment]
Also interested in this.

**Comment by ehsanul** [comment]
The Gerber files may be downloaded here (requires registration): https://www.pcbway.com/project/shareproject/Picoclick_C3_most_advanced_IOT_Button_98eb1819.html

**Comment by makermoekoe** [comment]
Added
