### ISSUE TITLE
Add second button to schematic, with same wakeup function

### ISSUE THREAD

**Issue by AshwinDeTaeye** [makermoekoe/Picoclick-C3#32]
Hello, 

I would like to add a second button to the schematic.
If possible have the same wake-up functionality as the first button.
Do I need to duplicate the below schematic completely for a second button?

![image](https://github.com/makermoekoe/Picoclick-C3/assets/74765848/93a44387-2029-4ae8-afd9-e8696b8570a2)

**Comment by makermoekoe** [comment]
Hey, you don't have to copy the whole circuit part. What's necessary for a second button are these components: SW1, R10, C19, R14 and D3. D3 is a dual diode, but you will only need one of them. The anode of the diode will be connected to the EN_LDO line.

**Comment by AshwinDeTaeye** [comment]
Hello, thanks. Just to be sure could you check the modified schematics?

![image](https://github.com/makermoekoe/Picoclick-C3/assets/74765848/881d1e14-b38b-43c0-a71f-c65e762acb77)
