### ISSUE TITLE
Break-out extra pins

### ISSUE THREAD

**Issue by cpq** [makermoekoe/Picoclick-C3#9]
It'd be cool to break out some (minimum 4) extra pins, as pads or as pin holes or as a miniature JST connector

**Comment by makermoekoe** [comment]
This is planned for the Picoclick C3, the big brother of the C3T which comes in the same package as the [Picoclick](https://github.com/makermoekoe/Picoclick). The linked, old Picoclick has external pins either.

**Comment by hallard** [comment]
yeah +1, an I2C QWIC connector would be perfect :-)
